### ISSUE TITLE
Internal server error when executing against /batch

### ISSUE THREAD

**Issue by nbbaier** [iyaja/llama-fs#9]
When I run the rollowing request:

```
 curl -X POST http://127.0.0.1:8000/batch \
-H "Content-Type: application/json" \
-d '{"path": "/Users/nicholasbaier/Downloads/", "instruction": "please suggest new names for these files"
}'
```

I get the error trace below:

```
INFO:     127.0.0.1:60292 - "POST /batch HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 52, in _try_loading_included_file_formats
    from llama_index.readers.file import (
ImportError: cannot import name 'DocxReader' from 'llama_index.readers.file' (/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/readers/file/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 426, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/llama-fs/server.py", line 74, in batch
    summaries = await get_dir_summaries(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/llama-fs/src/loader.py", line 20, in get_dir_summaries
    doc_dicts = load_documents(path)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/llama-fs/src/loader.py", line 64, in load_documents
    for docs in reader.iter_data():
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 750, in iter_data
    documents = SimpleDirectoryReader.load_file(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 511, in load_file
    default_file_reader_cls = SimpleDirectoryReader.supported_suffix_fn()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/nicholasbaier/.pyenv/versions/3.11.5/lib/python3.11/site-packages/llama_index/core/readers/file/base.py", line 66, in _try_loading_included_file_formats
    raise ImportError("`llama-index-readers-file` package not found")
ImportError: `llama-index-readers-file` package not found
```

**Comment by ioma8** [comment]
Same problem.
Internal Server Error

**Comment by vicmpen** [comment]
Managed to make it run, by creating an api key in groq and using my key in server.py and main.py. However, when running it against the sample directory i get a bunch of errors and 5/7 requests for the files return status code 429.

` Exception in ASGI application
Traceback (most recent call last):
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_async/connection.py", line 122, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/uvicorn/protocols/http/httptools_impl.py", line 399, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/server.py", line 74, in batch
    summaries = await get_dir_summaries(path)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/src/loader.py", line 23, in get_dir_summaries
    summaries = await get_summaries(doc_dicts)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/src/loader.py", line 186, in get_summaries
    summaries = await asyncio.gather(
                ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/src/loader.py", line 175, in dispatch_summarize_document
    return await summarize_image_document(doc, client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/src/loader.py", line 147, in summarize_image_document
    chat_completion = await client.chat(
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/ollama/_client.py", line 459, in chat
    return await self._request_stream(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/ollama/_client.py", line 380, in _request_stream
    response = await self._request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/ollama/_client.py", line 345, in _request
    response = await self._client.request(method, url, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/Users/vic/Desktop/projects/llama-fs/venv/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
/Users/vic/Desktop/projects/llama-fs/sample_data/text_files/dsflsdflj.txt
A personal description of someone who is easy-going, hardworking, and caring, with a strong emphasis on enjoying life and being dedicated to their job and relationships.
--------------------------------------------------------------------------------

/Users/vic/Desktop/projects/llama-fs/sample_data/random_file.txt
A text file containing a bank account number.
--------------------------------------------------------------------------------

Error status 429
Error status 429
Error status 429
Error status 429
Error status 429`

**Comment by kostebas** [comment]
> Same problem. Internal Server Error

same problem (( anybody knows how fix it ?
